package com.admissioncrm.applicationmgmtservice.Utills;

import com.admissioncrm.applicationmgmtservice.Dto.ApplicationFormRequestDTO.*;
import com.admissioncrm.applicationmgmtservice.Entities.ApplicationForm;
import org.springframework.stereotype.Component;

@Component
public class ApplicationFormMapper {

    public ApplicationForm mapToEntity(ApplicationFormSubmissionDTO dto) {
        ApplicationForm form = ApplicationForm.builder()
                .idUser(dto.getIdUser())

                // Personal Info
                .firstName(dto.getPersonalInfo().getFirstName())
                .middleName(dto.getPersonalInfo().getMiddleName())
                .lastName(dto.getPersonalInfo().getLastName())
                .fullName(dto.getPersonalInfo().getFullName())
                .email(dto.getPersonalInfo().getEmail())
                .studentMobile(dto.getPersonalInfo().getStudentMobile())
                .dob(dto.getPersonalInfo().getDob())
                .gender(dto.getPersonalInfo().getGender())
                .religion(dto.getPersonalInfo().getReligion())
                .nationality(dto.getPersonalInfo().getNationality())
                .casteCategory(dto.getPersonalInfo().getCasteCategory())
                .domicileState(dto.getPersonalInfo().getDomicileState())
                .differentlyAbled(dto.getPersonalInfo().getDifferentlyAbled())
                .disability(dto.getPersonalInfo().getDisability())
                .economicallyBackwardClass(dto.getPersonalInfo().getEconomicallyBackwardClass())

                // Parent Info
                .fatherSalutation(dto.getParentInfo().getFatherSalutation())
                .fatherName(dto.getParentInfo().getFatherName())
                .fatherMobile(dto.getParentInfo().getFatherMobile())
                .fatherEmail(dto.getParentInfo().getFatherEmail())
                .motherSalutation(dto.getParentInfo().getMotherSalutation())
                .motherName(dto.getParentInfo().getMotherName())
                .motherMobile(dto.getParentInfo().getMotherMobile())
                .motherEmail(dto.getParentInfo().getMotherEmail())
                .annualIncome(dto.getParentInfo().getAnnualIncome())

                // Address Info
                .country(dto.getAddressInfo().getCountry())
                .state(dto.getAddressInfo().getState())
                .district(dto.getAddressInfo().getDistrict())
                .cityTaluka(dto.getAddressInfo().getCityTaluka())
                .villageTown(dto.getAddressInfo().getVillageTown())
                .addressLine1(dto.getAddressInfo().getAddressLine1())
                .addressLine2(dto.getAddressInfo().getAddressLine2())
                .pincode(dto.getAddressInfo().getPincode())
                .permanentAddressSameAsCorrespondence(dto.getAddressInfo().getPermanentAddressSameAsCorrespondence())
                .countryPermanent(dto.getAddressInfo().getCountryPermanent())
                .statePermanent(dto.getAddressInfo().getStatePermanent())
                .districtPermanent(dto.getAddressInfo().getDistrictPermanent())
                .cityTalukaPermanent(dto.getAddressInfo().getCityTalukaPermanent())
                .villageTownPermanent(dto.getAddressInfo().getVillageTownPermanent())
                .addressLine1Permanent(dto.getAddressInfo().getAddressLine1Permanent())
                .addressLine2Permanent(dto.getAddressInfo().getAddressLine2Permanent())
                .pincodePermanent(dto.getAddressInfo().getPincodePermanent())

                // Academic Info
                .udiseNo(dto.getAcademicInfo().getUdiseNo())
                .abcId(dto.getAcademicInfo().getAbcId())
                .qualification(dto.getAcademicInfo().getQualification())
                .twelfthPassoutCountry(dto.getAcademicInfo().getTwelfthPassoutCountry())
                .twelfthPassoutState(dto.getAcademicInfo().getTwelfthPassoutState())
                .twelfthPassoutBoard(dto.getAcademicInfo().getTwelfthPassoutBoard())
                .twelfthSchoolName(dto.getAcademicInfo().getTwelfthSchoolName())
                .twelfthResultStatus(dto.getAcademicInfo().getTwelfthResultStatus())
                .twelfthSeatNumber(dto.getAcademicInfo().getTwelfthSeatNumber())
                .twelfthStream(dto.getAcademicInfo().getTwelfthStream())
                .twelfthPassingDate(dto.getAcademicInfo().getTwelfthPassingDate())
                .twelfthModeOfStudy(dto.getAcademicInfo().getTwelfthModeOfStudy())
                .twelfthMarkingScheme(dto.getAcademicInfo().getTwelfthMarkingScheme())
                .twelfthTotalMarks(dto.getAcademicInfo().getTwelfthTotalMarks())
                .twelfthObtainMarks(dto.getAcademicInfo().getTwelfthObtainMarks())
                .twelfthObtainCgpa(dto.getAcademicInfo().getTwelfthObtainCgpa())
                .courseInstituteName(dto.getAcademicInfo().getCourseInstituteName())
                .courseSeatNumber(dto.getAcademicInfo().getCourseSeatNumber())
                .courseBoardOrUniversity(dto.getAcademicInfo().getCourseBoardOrUniversity())
                .courseDegreeOrBranch(dto.getAcademicInfo().getCourseDegreeOrBranch())
                .courseSpecialization(dto.getAcademicInfo().getCourseSpecialization())
                .coursePassingDate(dto.getAcademicInfo().getCoursePassingDate())
                .courseResultStatus(dto.getAcademicInfo().getCourseResultStatus())
                .courseMarkingScheme(dto.getAcademicInfo().getCourseMarkingScheme())
                .courseMaximumMarks(dto.getAcademicInfo().getCourseMaximumMarks())
                .courseObtainMarks(dto.getAcademicInfo().getCourseObtainMarks())
                .courseObtainCgpaPercentage(dto.getAcademicInfo().getCourseObtainCgpaPercentage())

                // Entrance Exam Info
                .appearedForEntranceExam(dto.getEntranceExamInfo().getAppearedForEntranceExam())
                .entranceExam1(dto.getEntranceExamInfo().getEntranceExam1())
                .entrancePassingDate1(dto.getEntranceExamInfo().getEntrancePassingDate1())
                .entranceResultStatus1(dto.getEntranceExamInfo().getEntranceResultStatus1())
                .entranceScoreRankPercentile1(dto.getEntranceExamInfo().getEntranceScoreRankPercentile1())
                .entranceRollnoApplicationno1(dto.getEntranceExamInfo().getEntranceRollnoApplicationno1())
                .entranceExam2(dto.getEntranceExamInfo().getEntranceExam2())
                .entrancePassingDate2(dto.getEntranceExamInfo().getEntrancePassingDate2())
                .entranceResultStatus2(dto.getEntranceExamInfo().getEntranceResultStatus2())
                .entranceScoreRankPercentile2(dto.getEntranceExamInfo().getEntranceScoreRankPercentile2())
                .entranceRollnoApplicationno2(dto.getEntranceExamInfo().getEntranceRollnoApplicationno2())
                .entranceExam3(dto.getEntranceExamInfo().getEntranceExam3())
                .entrancePassingDate3(dto.getEntranceExamInfo().getEntrancePassingDate3())
                .entranceResultStatus3(dto.getEntranceExamInfo().getEntranceResultStatus3())
                .entranceScoreRankPercentile3(dto.getEntranceExamInfo().getEntranceScoreRankPercentile3())
                .entranceRollnoApplicationno3(dto.getEntranceExamInfo().getEntranceRollnoApplicationno3())
                .entranceExam4(dto.getEntranceExamInfo().getEntranceExam4())
                .entrancePassingDate4(dto.getEntranceExamInfo().getEntrancePassingDate4())
                .entranceResultStatus4(dto.getEntranceExamInfo().getEntranceResultStatus4())
                .entranceScoreRankPercentile4(dto.getEntranceExamInfo().getEntranceScoreRankPercentile4())
                .entranceRollnoApplicationno4(dto.getEntranceExamInfo().getEntranceRollnoApplicationno4())
                .registeredInAcpcAcpdc(dto.getEntranceExamInfo().getRegisteredInAcpcAcpdc())
                .acpcMeritNumber(dto.getEntranceExamInfo().getAcpcMeritNumber())
                .acpcMeritMarks(dto.getEntranceExamInfo().getAcpcMeritMarks())
                .acpcApplicationNumber(dto.getEntranceExamInfo().getAcpcApplicationNumber())

                // Additional Info
                .educationLoanRequired(dto.getAdditionalInfo().getEducationLoanRequired())
                .hostelAccommodationRequired(dto.getAdditionalInfo().getHostelAccommodationRequired())
                .transportationRequired(dto.getAdditionalInfo().getTransportationRequired())
                .heardAboutUniversityFrom(dto.getAdditionalInfo().getHeardAboutUniversityFrom())
                .studentOfUniversity(dto.getAdditionalInfo().getStudentOfUniversity())
                .enrollmentNumber(dto.getAdditionalInfo().getEnrollmentNumber())

                .build();

        return form;
    }


    public ApplicationFormSubmissionDTO mapToDTO(ApplicationForm form) {
        return ApplicationFormSubmissionDTO.builder()
                .idUser(form.getIdUser())

                .personalInfo(
                        PersonalInfoDTO.builder()
                                .firstName(form.getFirstName())
                                .middleName(form.getMiddleName())
                                .lastName(form.getLastName())
                                .fullName(form.getFullName())
                                .email(form.getEmail())
                                .studentMobile(form.getStudentMobile())
                                .dob(form.getDob())
                                .gender(form.getGender())
                                .religion(form.getReligion())
                                .nationality(form.getNationality())
                                .casteCategory(form.getCasteCategory())
                                .domicileState(form.getDomicileState())
                                .differentlyAbled(form.getDifferentlyAbled())
                                .disability(form.getDisability())
                                .economicallyBackwardClass(form.getEconomicallyBackwardClass())
                                .build()
                )

                .parentInfo(
                        ParentInfoDTO.builder()
                                .fatherSalutation(form.getFatherSalutation())
                                .fatherName(form.getFatherName())
                                .fatherMobile(form.getFatherMobile())
                                .fatherEmail(form.getFatherEmail())
                                .motherSalutation(form.getMotherSalutation())
                                .motherName(form.getMotherName())
                                .motherMobile(form.getMotherMobile())
                                .motherEmail(form.getMotherEmail())
                                .annualIncome(form.getAnnualIncome())
                                .build()
                )

                .addressInfo(
                        AddressInfoDTO.builder()
                                .country(form.getCountry())
                                .state(form.getState())
                                .district(form.getDistrict())
                                .cityTaluka(form.getCityTaluka())
                                .villageTown(form.getVillageTown())
                                .addressLine1(form.getAddressLine1())
                                .addressLine2(form.getAddressLine2())
                                .pincode(form.getPincode())
                                .permanentAddressSameAsCorrespondence(form.getPermanentAddressSameAsCorrespondence())
                                .countryPermanent(form.getCountryPermanent())
                                .statePermanent(form.getStatePermanent())
                                .districtPermanent(form.getDistrictPermanent())
                                .cityTalukaPermanent(form.getCityTalukaPermanent())
                                .villageTownPermanent(form.getVillageTownPermanent())
                                .addressLine1Permanent(form.getAddressLine1Permanent())
                                .addressLine2Permanent(form.getAddressLine2Permanent())
                                .pincodePermanent(form.getPincodePermanent())
                                .build()
                )

                .academicInfo(
                        AcademicInfoDTO.builder()
                                .udiseNo(form.getUdiseNo())
                                .abcId(form.getAbcId())
                                .qualification(form.getQualification())
                                .twelfthPassoutCountry(form.getTwelfthPassoutCountry())
                                .twelfthPassoutState(form.getTwelfthPassoutState())
                                .twelfthPassoutBoard(form.getTwelfthPassoutBoard())
                                .twelfthSchoolName(form.getTwelfthSchoolName())
                                .twelfthResultStatus(form.getTwelfthResultStatus())
                                .twelfthSeatNumber(form.getTwelfthSeatNumber())
                                .twelfthStream(form.getTwelfthStream())
                                .twelfthPassingDate(form.getTwelfthPassingDate())
                                .twelfthModeOfStudy(form.getTwelfthModeOfStudy())
                                .twelfthMarkingScheme(form.getTwelfthMarkingScheme())
                                .twelfthTotalMarks(form.getTwelfthTotalMarks())
                                .twelfthObtainMarks(form.getTwelfthObtainMarks())
                                .twelfthObtainCgpa(form.getTwelfthObtainCgpa())
                                .courseInstituteName(form.getCourseInstituteName())
                                .courseSeatNumber(form.getCourseSeatNumber())
                                .courseBoardOrUniversity(form.getCourseBoardOrUniversity())
                                .courseDegreeOrBranch(form.getCourseDegreeOrBranch())
                                .courseSpecialization(form.getCourseSpecialization())
                                .coursePassingDate(form.getCoursePassingDate())
                                .courseResultStatus(form.getCourseResultStatus())
                                .courseMarkingScheme(form.getCourseMarkingScheme())
                                .courseMaximumMarks(form.getCourseMaximumMarks())
                                .courseObtainMarks(form.getCourseObtainMarks())
                                .courseObtainCgpaPercentage(form.getCourseObtainCgpaPercentage())
                                .build()
                )

                .entranceExamInfo(
                        EntranceExamInfoDTO.builder()
                                .appearedForEntranceExam(form.getAppearedForEntranceExam())
                                .entranceExam1(form.getEntranceExam1())
                                .entrancePassingDate1(form.getEntrancePassingDate1())
                                .entranceResultStatus1(form.getEntranceResultStatus1())
                                .entranceScoreRankPercentile1(form.getEntranceScoreRankPercentile1())
                                .entranceRollnoApplicationno1(form.getEntranceRollnoApplicationno1())
                                .entranceExam2(form.getEntranceExam2())
                                .entrancePassingDate2(form.getEntrancePassingDate2())
                                .entranceResultStatus2(form.getEntranceResultStatus2())
                                .entranceScoreRankPercentile2(form.getEntranceScoreRankPercentile2())
                                .entranceRollnoApplicationno2(form.getEntranceRollnoApplicationno2())
                                .entranceExam3(form.getEntranceExam3())
                                .entrancePassingDate3(form.getEntrancePassingDate3())
                                .entranceResultStatus3(form.getEntranceResultStatus3())
                                .entranceScoreRankPercentile3(form.getEntranceScoreRankPercentile3())
                                .entranceRollnoApplicationno3(form.getEntranceRollnoApplicationno3())
                                .entranceExam4(form.getEntranceExam4())
                                .entrancePassingDate4(form.getEntrancePassingDate4())
                                .entranceResultStatus4(form.getEntranceResultStatus4())
                                .entranceScoreRankPercentile4(form.getEntranceScoreRankPercentile4())
                                .entranceRollnoApplicationno4(form.getEntranceRollnoApplicationno4())
                                .registeredInAcpcAcpdc(form.getRegisteredInAcpcAcpdc())
                                .acpcMeritNumber(form.getAcpcMeritNumber())
                                .acpcMeritMarks(form.getAcpcMeritMarks())
                                .acpcApplicationNumber(form.getAcpcApplicationNumber())
                                .build()
                )

                .additionalInfo(
                        AdditionalInfoDTO.builder()
                                .educationLoanRequired(form.getEducationLoanRequired())
                                .hostelAccommodationRequired(form.getHostelAccommodationRequired())
                                .transportationRequired(form.getTransportationRequired())
                                .heardAboutUniversityFrom(form.getHeardAboutUniversityFrom())
                                .studentOfUniversity(form.getStudentOfUniversity())
                                .enrollmentNumber(form.getEnrollmentNumber())
                                .build()
                )

                .build();
    }

}