package com.admission_crm.lead_management.Payload.Response.Leads;

import com.admission_crm.lead_management.Payload.Response.LeadResponse;
import lombok.Data;

import java.time.LocalDateTime;
@Data
public class LeadFollowUpResponse {
    private String id;                  // follow-up id (generated by DB)
    private String leadId;              // which lead this follow-up belongs to
    private LocalDateTime followUpDateTime; // scheduled datetime
    private String type;              // CALL, EMAIL, MEETING, VIDEO_CALL
    private String priority;          // LOW, MEDIUM, HIGH, URGENT
    private String notes;             // extra notes
    private Integer reminder;         // reminder in minutes
    private LocalDateTime createdAt;  // when this follow-up was created
    private LocalDateTime updatedAt;  // last updated time
    private String status;            // e.g. PENDING, COMPLETED, MISSED

    LeadResponse lead; // basic lead info (id, name, email, phone)
}