package com.admissioncrm.applicationmgmtservice.Services;

import com.admissioncrm.applicationmgmtservice.Controllers.ApplicationController;
import com.admissioncrm.applicationmgmtservice.Dto.ApplicationFormRequestDto;
import com.admissioncrm.applicationmgmtservice.Entities.ApplicationForm;
import org.springframework.stereotype.Service;

@Service
public class ApplicationService {


    public void  saveApplication(ApplicationFormRequestDto request){

        ApplicationForm application =applicationDtoToEntity(request);



    }

    private ApplicationForm applicationDtoToEntity(ApplicationFormRequestDto dto) {
        return ApplicationForm.builder()
                .idUser(dto.getIdUser())
                .instituteCourseId(dto.getInstituteCourseId())
                .fullName(dto.getFullName())
                .lastName(dto.getLastName())
                .middleName(dto.getMiddleName())
                .firstName(dto.getFirstName())
                .email(dto.getEmail())
                .studentMobile(dto.getStudentMobile())
                .dob(dto.getDob())
                .gender(dto.getGender())
                .religion(dto.getReligion())
                .nationality(dto.getNationality())
                .casteCategory(dto.getCasteCategory())
                .domicileState(dto.getDomicileState())
                .differentlyAbled(dto.getDifferentlyAbled())
                .disability(dto.getDisability())
                .economicallyBackwardClass(dto.getEconomicallyBackwardClass())
                .fatherSalutation(dto.getFatherSalutation())
                .fatherName(dto.getFatherName())
                .fatherMobile(dto.getFatherMobile())
                .fatherEmail(dto.getFatherEmail())
                .motherSalutation(dto.getMotherSalutation())
                .motherName(dto.getMotherName())
                .motherMobile(dto.getMotherMobile())
                .motherEmail(dto.getMotherEmail())
                .annualIncome(dto.getAnnualIncome())
                .country(dto.getCountry())
                .state(dto.getState())
                .district(dto.getDistrict())
                .cityTaluka(dto.getCityTaluka())
                .villageTown(dto.getVillageTown())
                .addressLine1(dto.getAddressLine1())
                .addressLine2(dto.getAddressLine2())
                .pincode(dto.getPincode())
                .permanentAddressSameAsCorrespondence(dto.getPermanentAddressSameAsCorrespondence())
                .countryPermanent(dto.getCountryPermanent())
                .statePermanent(dto.getStatePermanent())
                .districtPermanent(dto.getDistrictPermanent())
                .cityTalukaPermanent(dto.getCityTalukaPermanent())
                .villageTownPermanent(dto.getVillageTownPermanent())
                .addressLine1Permanent(dto.getAddressLine1Permanent())
                .addressLine2Permanent(dto.getAddressLine2Permanent())
                .pincodePermanent(dto.getPincodePermanent())
                .udiseNo(dto.getUdiseNo())
                .abcId(dto.getAbcId())
                .qualification(dto.getQualification())
                .twelfthPassoutCountry(dto.getTwelfthPassoutCountry())
                .twelfthPassoutState(dto.getTwelfthPassoutState())
                .twelfthPassoutBoard(dto.getTwelfthPassoutBoard())
                .twelfthSchoolName(dto.getTwelfthSchoolName())
                .twelfthResultStatus(dto.getTwelfthResultStatus())
                .twelfthSeatNumber(dto.getTwelfthSeatNumber())
                .twelfthStream(dto.getTwelfthStream())
                .twelfthPassingDate(dto.getTwelfthPassingDate())
                .twelfthModeOfStudy(dto.getTwelfthModeOfStudy())
                .twelfthMarkingScheme(dto.getTwelfthMarkingScheme())
                .twelfthTotalMarks(dto.getTwelfthTotalMarks())
                .twelfthObtainMarks(dto.getTwelfthObtainMarks())
                .twelfthObtainCgpa(dto.getTwelfthObtainCgpa())
                .courseInstituteName(dto.getCourseInstituteName())
                .courseSeatNumber(dto.getCourseSeatNumber())
                .courseBoardOrUniversity(dto.getCourseBoardOrUniversity())
                .courseDegreeOrBranch(dto.getCourseDegreeOrBranch())
                .courseSpecialization(dto.getCourseSpecialization())
                .coursePassingDate(dto.getCoursePassingDate())
                .courseResultStatus(dto.getCourseResultStatus())
                .courseMarkingScheme(dto.getCourseMarkingScheme())
                .courseMaximumMarks(dto.getCourseMaximumMarks())
                .courseObtainMarks(dto.getCourseObtainMarks())
                .courseObtainCgpaPercentage(dto.getCourseObtainCgpaPercentage())
                .appearedForEntranceExam(dto.getAppearedForEntranceExam())
                .entranceExam1(dto.getEntranceExam1())
                .entrancePassingDate1(dto.getEntrancePassingDate1())
                .entranceResultStatus1(dto.getEntranceResultStatus1())
                .entranceScoreRankPercentile1(dto.getEntranceScoreRankPercentile1())
                .entranceRollnoApplicationno1(dto.getEntranceRollnoApplicationno1())
                .entranceExam2(dto.getEntranceExam2())
                .entrancePassingDate2(dto.getEntrancePassingDate2())
                .entranceResultStatus2(dto.getEntranceResultStatus2())
                .entranceScoreRankPercentile2(dto.getEntranceScoreRankPercentile2())
                .entranceRollnoApplicationno2(dto.getEntranceRollnoApplicationno2())
                .entranceExam3(dto.getEntranceExam3())
                .entrancePassingDate3(dto.getEntrancePassingDate3())
                .entranceResultStatus3(dto.getEntranceResultStatus3())
                .entranceScoreRankPercentile3(dto.getEntranceScoreRankPercentile3())
                .entranceRollnoApplicationno3(dto.getEntranceRollnoApplicationno3())
                .entranceExam4(dto.getEntranceExam4())
                .entrancePassingDate4(dto.getEntrancePassingDate4())
                .entranceResultStatus4(dto.getEntranceResultStatus4())
                .entranceScoreRankPercentile4(dto.getEntranceScoreRankPercentile4())
                .entranceRollnoApplicationno4(dto.getEntranceRollnoApplicationno4())
                .registeredInAcpcAcpdc(dto.getRegisteredInAcpcAcpdc())
                .acpcMeritNumber(dto.getAcpcMeritNumber())
                .acpcMeritMarks(dto.getAcpcMeritMarks())
                .acpcApplicationNumber(dto.getAcpcApplicationNumber())
                .educationLoanRequired(dto.getEducationLoanRequired())
                .hostelAccommodationRequired(dto.getHostelAccommodationRequired())
                .transportationRequired(dto.getTransportationRequired())
                .heardAboutUniversityFrom(dto.getHeardAboutUniversityFrom())
                .studentOfUniversity(dto.getStudentOfUniversity())
                .enrollmentNumber(dto.getEnrollmentNumber())
                .build();
    }
}
